version: "3.7"
services:
  songrec:
    build: ./recommender 
    ports:
      - "8000:8000"
  
  webapp:
    build: ./api
    depends_on: 
      - songrec
    volumes:
      - data
    ports:
      - "5000:5000"

volumes:
  data: genius_copy_data:/data
